[package]
name = "volumectl"
version = "0.1.0"
authors = ["Philipp Gürtler"]
edition = "2018"

[dependencies]
libpulse-binding = "2.6.0"
clap = "2.33.0"
dirs = "1.0.5"
regex = "1.1.6"
simple-error = "0.1.13"
lazy_static = "1.3.0"